import { z } from 'zod';

// 체결가 필드 (46개) — Python snake_case → TS camelCase
export const EXECUTION_FIELD_NAMES = [
  'mkscShrnIscd',
  'stckCntgHour',
  'stckPrpr',
  'prdyVrssSign',
  'prdyVrss',
  'prdyCtrt',
  'wghnAvrgStckPrc',
  'stckOprc',
  'stckHgpr',
  'stckLwpr',
  'askp1',
  'bidp1',
  'cntgVol',
  'acmlVol',
  'acmlTrPbmn',
  'selnCntgCsnu',
  'shnuCntgCsnu',
  'ntbyCntgCsnu',
  'cttr',
  'selnCntgSmtn',
  'shnuCntgSmtn',
  'cntgClsCode',
  'shnuRate',
  'prdyVolVrssAcmlVolRate',
  'oprcHour',
  'oprcVrssPrprSign',
  'oprcVrssPrpr',
  'hgprHour',
  'hgprVrssPrprSign',
  'hgprVrssPrpr',
  'lwprHour',
  'lwprVrssPrprSign',
  'lwprVrssPrpr',
  'bsopDate',
  'newMkopClsCode',
  'trhtYn',
  'askpRsqn1',
  'bidpRsqn1',
  'totalAskpRsqn',
  'totalBidpRsqn',
  'volTnrt',
  'prdySmnsHourAcmlVol',
  'prdySmnsHourAcmlVolRate',
  'hourClsCode',
  'mrktTrtmClsCode',
  'viStndPrc',
] as const;

// 호가 필드 (59개)
export const ORDERBOOK_FIELD_NAMES = [
  'mkscShrnIscd',
  'bsopHour',
  'hourClsCode',
  'askp1',
  'askp2',
  'askp3',
  'askp4',
  'askp5',
  'askp6',
  'askp7',
  'askp8',
  'askp9',
  'askp10',
  'bidp1',
  'bidp2',
  'bidp3',
  'bidp4',
  'bidp5',
  'bidp6',
  'bidp7',
  'bidp8',
  'bidp9',
  'bidp10',
  'askpRsqn1',
  'askpRsqn2',
  'askpRsqn3',
  'askpRsqn4',
  'askpRsqn5',
  'askpRsqn6',
  'askpRsqn7',
  'askpRsqn8',
  'askpRsqn9',
  'askpRsqn10',
  'bidpRsqn1',
  'bidpRsqn2',
  'bidpRsqn3',
  'bidpRsqn4',
  'bidpRsqn5',
  'bidpRsqn6',
  'bidpRsqn7',
  'bidpRsqn8',
  'bidpRsqn9',
  'bidpRsqn10',
  'totalAskpRsqn',
  'totalBidpRsqn',
  'ovtmTotalAskpRsqn',
  'ovtmTotalBidpRsqn',
  'antcCnpr',
  'antcCnqn',
  'antcVol',
  'antcCntgVrss',
  'antcCntgVrssSign',
  'antcCntgPrdyCtrt',
  'acmlVol',
  'totalAskpRsqnIcdc',
  'totalBidpRsqnIcdc',
  'ovtmTotalAskpIcdc',
  'ovtmTotalBidpIcdc',
  'stckDealClsCode',
] as const;

// 체결통보 필드 (26개)
export const EXECUTION_NOTIFICATION_FIELD_NAMES = [
  'custId',
  'acntNo',
  'oderNo',
  'ooderNo',
  'selnByovCls',
  'rctfCls',
  'oderKind',
  'oderCond',
  'stckShrnIscd',
  'cntgQty',
  'cntgUnpr',
  'stckCntgHour',
  'rfusYn',
  'cntgYn',
  'acptYn',
  'brncNo',
  'oderQty',
  'acntName',
  'ordCondPrc',
  'ordExgGb',
  'popupYn',
  'filler',
  'crdtCls',
  'crdtLoanDate',
  'cntgIsnm40',
  'oderPrc',
] as const;

// Zod schemas — all fields are strings
export const domesticRealtimeExecutionSchema = z.object({
  mkscShrnIscd: z.string(),
  stckCntgHour: z.string(),
  stckPrpr: z.string(),
  prdyVrssSign: z.string(),
  prdyVrss: z.string(),
  prdyCtrt: z.string(),
  wghnAvrgStckPrc: z.string(),
  stckOprc: z.string(),
  stckHgpr: z.string(),
  stckLwpr: z.string(),
  askp1: z.string(),
  bidp1: z.string(),
  cntgVol: z.string(),
  acmlVol: z.string(),
  acmlTrPbmn: z.string(),
  selnCntgCsnu: z.string(),
  shnuCntgCsnu: z.string(),
  ntbyCntgCsnu: z.string(),
  cttr: z.string(),
  selnCntgSmtn: z.string(),
  shnuCntgSmtn: z.string(),
  cntgClsCode: z.string(),
  shnuRate: z.string(),
  prdyVolVrssAcmlVolRate: z.string(),
  oprcHour: z.string(),
  oprcVrssPrprSign: z.string(),
  oprcVrssPrpr: z.string(),
  hgprHour: z.string(),
  hgprVrssPrprSign: z.string(),
  hgprVrssPrpr: z.string(),
  lwprHour: z.string(),
  lwprVrssPrprSign: z.string(),
  lwprVrssPrpr: z.string(),
  bsopDate: z.string(),
  newMkopClsCode: z.string(),
  trhtYn: z.string(),
  askpRsqn1: z.string(),
  bidpRsqn1: z.string(),
  totalAskpRsqn: z.string(),
  totalBidpRsqn: z.string(),
  volTnrt: z.string(),
  prdySmnsHourAcmlVol: z.string(),
  prdySmnsHourAcmlVolRate: z.string(),
  hourClsCode: z.string(),
  mrktTrtmClsCode: z.string(),
  viStndPrc: z.string(),
});

export const domesticRealtimeOrderbookSchema = z.object({
  mkscShrnIscd: z.string(),
  bsopHour: z.string(),
  hourClsCode: z.string(),
  askp1: z.string(),
  askp2: z.string(),
  askp3: z.string(),
  askp4: z.string(),
  askp5: z.string(),
  askp6: z.string(),
  askp7: z.string(),
  askp8: z.string(),
  askp9: z.string(),
  askp10: z.string(),
  bidp1: z.string(),
  bidp2: z.string(),
  bidp3: z.string(),
  bidp4: z.string(),
  bidp5: z.string(),
  bidp6: z.string(),
  bidp7: z.string(),
  bidp8: z.string(),
  bidp9: z.string(),
  bidp10: z.string(),
  askpRsqn1: z.string(),
  askpRsqn2: z.string(),
  askpRsqn3: z.string(),
  askpRsqn4: z.string(),
  askpRsqn5: z.string(),
  askpRsqn6: z.string(),
  askpRsqn7: z.string(),
  askpRsqn8: z.string(),
  askpRsqn9: z.string(),
  askpRsqn10: z.string(),
  bidpRsqn1: z.string(),
  bidpRsqn2: z.string(),
  bidpRsqn3: z.string(),
  bidpRsqn4: z.string(),
  bidpRsqn5: z.string(),
  bidpRsqn6: z.string(),
  bidpRsqn7: z.string(),
  bidpRsqn8: z.string(),
  bidpRsqn9: z.string(),
  bidpRsqn10: z.string(),
  totalAskpRsqn: z.string(),
  totalBidpRsqn: z.string(),
  ovtmTotalAskpRsqn: z.string(),
  ovtmTotalBidpRsqn: z.string(),
  antcCnpr: z.string(),
  antcCnqn: z.string(),
  antcVol: z.string(),
  antcCntgVrss: z.string(),
  antcCntgVrssSign: z.string(),
  antcCntgPrdyCtrt: z.string(),
  acmlVol: z.string(),
  totalAskpRsqnIcdc: z.string(),
  totalBidpRsqnIcdc: z.string(),
  ovtmTotalAskpIcdc: z.string(),
  ovtmTotalBidpIcdc: z.string(),
  stckDealClsCode: z.string(),
});

export const domesticRealtimeExecutionNotificationSchema = z.object({
  custId: z.string(),
  acntNo: z.string(),
  oderNo: z.string(),
  ooderNo: z.string(),
  selnByovCls: z.string(),
  rctfCls: z.string(),
  oderKind: z.string(),
  oderCond: z.string(),
  stckShrnIscd: z.string(),
  cntgQty: z.string(),
  cntgUnpr: z.string(),
  stckCntgHour: z.string(),
  rfusYn: z.string(),
  cntgYn: z.string(),
  acptYn: z.string(),
  brncNo: z.string(),
  oderQty: z.string(),
  acntName: z.string(),
  ordCondPrc: z.string(),
  ordExgGb: z.string(),
  popupYn: z.string(),
  filler: z.string(),
  crdtCls: z.string(),
  crdtLoanDate: z.string(),
  cntgIsnm40: z.string(),
  oderPrc: z.string(),
});

export type DomesticRealtimeExecutionItem = z.infer<typeof domesticRealtimeExecutionSchema>;
export type DomesticRealtimeOrderbookItem = z.infer<typeof domesticRealtimeOrderbookSchema>;
export type DomesticRealtimeExecutionNotificationItem = z.infer<typeof domesticRealtimeExecutionNotificationSchema>;
