import { z } from 'zod';

// 채권체결 필드 (19개)
export const BOND_EXECUTION_FIELD_NAMES = [
  'stndIscd',
  'bondIsnm',
  'stckCntgHour',
  'prdyVrssSign',
  'prdyVrss',
  'prdyCtrt',
  'stckPrpr',
  'cntgVol',
  'stckOprc',
  'stckHgpr',
  'stckLwpr',
  'stckPrdyClpr',
  'bondCntgErt',
  'oprcErt',
  'hgprErt',
  'lwprErt',
  'acmlVol',
  'prdyVol',
  'cntgTypeClsCode',
] as const;

// 채권호가 필드 (34개) — 호가 단계별로 수익률·가격·잔량이 매도/매수 교차로 온다 (스펙 순서)
export const BOND_ORDERBOOK_FIELD_NAMES = [
  'stndIscd',
  'stckCntgHour',
  'askpErt1',
  'bidpErt1',
  'askp1',
  'bidp1',
  'askpRsqn1',
  'bidpRsqn1',
  'askpErt2',
  'bidpErt2',
  'askp2',
  'bidp2',
  'askpRsqn2',
  'bidpRsqn2',
  'askpErt3',
  'bidpErt3',
  'askp3',
  'bidp3',
  'askpRsqn3',
  'bidpRsqn3',
  'askpErt4',
  'bidpErt4',
  'askp4',
  'bidp4',
  'askpRsqn4',
  'bidpRsqn4',
  'askpErt5',
  'bidpErt5',
  'askp5',
  'bidp5',
  'askpRsqn5',
  'bidpRsqn5',
  'totalAskpRsqn',
  'totalBidpRsqn',
] as const;

// 채권지수체결 필드 (20개)
export const BOND_INDEX_EXECUTION_FIELD_NAMES = [
  'nmixId',
  'stndDate1',
  'trnmHour',
  'totlErnnNmixOprc',
  'totlErnnNmixHgpr',
  'totlErnnNmixLwpr',
  'totlErnnNmix',
  'prdyTotlErnnNmix',
  'totlErnnNmixPrdyVrss',
  'totlErnnNmixPrdyVrssSign',
  'totlErnnNmixPrdyCtrt',
  'clenPrcNmix',
  'mrktPrcNmix',
  'bondCallRnvsNmix',
  'bondZeroRnvsNmix',
  'bondFutsThpr',
  'bondAvrgDrtnVal',
  'bondAvrgCnvxVal',
  'bondAvrgYtmVal',
  'bondAvrgFrdlYtmVal',
] as const;

// Zod schemas — all fields are strings
export const bondRealtimeExecutionSchema = z.object({
  stndIscd: z.string(),
  bondIsnm: z.string(),
  stckCntgHour: z.string(),
  prdyVrssSign: z.string(),
  prdyVrss: z.string(),
  prdyCtrt: z.string(),
  stckPrpr: z.string(),
  cntgVol: z.string(),
  stckOprc: z.string(),
  stckHgpr: z.string(),
  stckLwpr: z.string(),
  stckPrdyClpr: z.string(),
  bondCntgErt: z.string(),
  oprcErt: z.string(),
  hgprErt: z.string(),
  lwprErt: z.string(),
  acmlVol: z.string(),
  prdyVol: z.string(),
  cntgTypeClsCode: z.string(),
});

export const bondRealtimeOrderbookSchema = z.object({
  stndIscd: z.string(),
  stckCntgHour: z.string(),
  askpErt1: z.string(),
  askpErt2: z.string(),
  askpErt3: z.string(),
  askpErt4: z.string(),
  askpErt5: z.string(),
  bidpErt1: z.string(),
  bidpErt2: z.string(),
  bidpErt3: z.string(),
  bidpErt4: z.string(),
  bidpErt5: z.string(),
  askp1: z.string(),
  askp2: z.string(),
  askp3: z.string(),
  askp4: z.string(),
  askp5: z.string(),
  bidp1: z.string(),
  bidp2: z.string(),
  bidp3: z.string(),
  bidp4: z.string(),
  bidp5: z.string(),
  askpRsqn1: z.string(),
  askpRsqn2: z.string(),
  askpRsqn3: z.string(),
  askpRsqn4: z.string(),
  askpRsqn5: z.string(),
  bidpRsqn1: z.string(),
  bidpRsqn2: z.string(),
  bidpRsqn3: z.string(),
  bidpRsqn4: z.string(),
  bidpRsqn5: z.string(),
  totalAskpRsqn: z.string(),
  totalBidpRsqn: z.string(),
});

export const bondRealtimeIndexExecutionSchema = z.object({
  nmixId: z.string(),
  stndDate1: z.string(),
  trnmHour: z.string(),
  totlErnnNmixOprc: z.string(),
  totlErnnNmixHgpr: z.string(),
  totlErnnNmixLwpr: z.string(),
  totlErnnNmix: z.string(),
  prdyTotlErnnNmix: z.string(),
  totlErnnNmixPrdyVrss: z.string(),
  totlErnnNmixPrdyVrssSign: z.string(),
  totlErnnNmixPrdyCtrt: z.string(),
  clenPrcNmix: z.string(),
  mrktPrcNmix: z.string(),
  bondCallRnvsNmix: z.string(),
  bondZeroRnvsNmix: z.string(),
  bondFutsThpr: z.string(),
  bondAvrgDrtnVal: z.string(),
  bondAvrgCnvxVal: z.string(),
  bondAvrgYtmVal: z.string(),
  bondAvrgFrdlYtmVal: z.string(),
});

export type BondRealtimeExecutionItem = z.infer<typeof bondRealtimeExecutionSchema>;
export type BondRealtimeOrderbookItem = z.infer<typeof bondRealtimeOrderbookSchema>;
export type BondRealtimeIndexExecutionItem = z.infer<typeof bondRealtimeIndexExecutionSchema>;
