import { z } from 'zod';

// 해외주식 실시간 호가 필드 (71개) — TR_ID: HDFSASP0
export const OVERSEAS_ORDERBOOK_FIELD_NAMES = [
  'rsym',
  'symb',
  'zdiv',
  'xymd',
  'xhms',
  'kymd',
  'khms',
  'bvol',
  'avol',
  'bdvl',
  'advl',
  'pbid1',
  'pask1',
  'vbid1',
  'vask1',
  'dbid1',
  'dask1',
  'pbid2',
  'pask2',
  'vbid2',
  'vask2',
  'dbid2',
  'dask2',
  'pbid3',
  'pask3',
  'vbid3',
  'vask3',
  'dbid3',
  'dask3',
  'pbid4',
  'pask4',
  'vbid4',
  'vask4',
  'dbid4',
  'dask4',
  'pbid5',
  'pask5',
  'vbid5',
  'vask5',
  'dbid5',
  'dask5',
  'pbid6',
  'pask6',
  'vbid6',
  'vask6',
  'dbid6',
  'dask6',
  'pbid7',
  'pask7',
  'vbid7',
  'vask7',
  'dbid7',
  'dask7',
  'pbid8',
  'pask8',
  'vbid8',
  'vask8',
  'dbid8',
  'dask8',
  'pbid9',
  'pask9',
  'vbid9',
  'vask9',
  'dbid9',
  'dask9',
  'pbid10',
  'pask10',
  'vbid10',
  'vask10',
  'dbid10',
  'dask10',
] as const;

// 해외주식 지연호가(아시아) 필드 (17개) — TR_ID: HDFSASP1
export const OVERSEAS_DELAYED_ORDERBOOK_FIELD_NAMES = [
  'rsym',
  'symb',
  'zdiv',
  'xymd',
  'xhms',
  'kymd',
  'khms',
  'bvol',
  'avol',
  'bdvl',
  'advl',
  'pbid1',
  'pask1',
  'vbid1',
  'vask1',
  'dbid1',
  'dask1',
] as const;

// 해외주식 실시간지연체결가 필드 (26개) — TR_ID: HDFSCNT0
export const OVERSEAS_EXECUTION_FIELD_NAMES = [
  'rsym',
  'symb',
  'zdiv',
  'tymd',
  'xymd',
  'xhms',
  'kymd',
  'khms',
  'open',
  'high',
  'low',
  'last',
  'sign',
  'diff',
  'rate',
  'pbid',
  'pask',
  'vbid',
  'vask',
  'evol',
  'tvol',
  'tamt',
  'bivl',
  'asvl',
  'strn',
  'mtyp',
] as const;

// 해외주식 실시간체결통보 필드 (25개) — TR_ID: H0GSCNI0
export const OVERSEAS_EXECUTION_NOTIFICATION_FIELD_NAMES = [
  'custId',
  'acntNo',
  'oderNo',
  'ooderNo',
  'selnByovCls',
  'rctfCls',
  'oderKind2',
  'stckShrnIscd',
  'cntgQty',
  'cntgUnpr',
  'stckCntgHour',
  'rfusYn',
  'cntgYn',
  'acptYn',
  'brncNo',
  'oderQty',
  'acntName',
  'cntgIsnm',
  'oderCond',
  'debtGb',
  'debtDate',
  'startTm',
  'endTm',
  'tmDivTp',
  'cntgUnpr12',
] as const;

// Zod schemas — all fields are strings
export const overseasRealtimeOrderbookSchema = z.object({
  rsym: z.string(),
  symb: z.string(),
  zdiv: z.string(),
  xymd: z.string(),
  xhms: z.string(),
  kymd: z.string(),
  khms: z.string(),
  bvol: z.string(),
  avol: z.string(),
  bdvl: z.string(),
  advl: z.string(),
  pbid1: z.string(),
  pask1: z.string(),
  vbid1: z.string(),
  vask1: z.string(),
  dbid1: z.string(),
  dask1: z.string(),
  pbid2: z.string(),
  pask2: z.string(),
  vbid2: z.string(),
  vask2: z.string(),
  dbid2: z.string(),
  dask2: z.string(),
  pbid3: z.string(),
  pask3: z.string(),
  vbid3: z.string(),
  vask3: z.string(),
  dbid3: z.string(),
  dask3: z.string(),
  pbid4: z.string(),
  pask4: z.string(),
  vbid4: z.string(),
  vask4: z.string(),
  dbid4: z.string(),
  dask4: z.string(),
  pbid5: z.string(),
  pask5: z.string(),
  vbid5: z.string(),
  vask5: z.string(),
  dbid5: z.string(),
  dask5: z.string(),
  pbid6: z.string(),
  pask6: z.string(),
  vbid6: z.string(),
  vask6: z.string(),
  dbid6: z.string(),
  dask6: z.string(),
  pbid7: z.string(),
  pask7: z.string(),
  vbid7: z.string(),
  vask7: z.string(),
  dbid7: z.string(),
  dask7: z.string(),
  pbid8: z.string(),
  pask8: z.string(),
  vbid8: z.string(),
  vask8: z.string(),
  dbid8: z.string(),
  dask8: z.string(),
  pbid9: z.string(),
  pask9: z.string(),
  vbid9: z.string(),
  vask9: z.string(),
  dbid9: z.string(),
  dask9: z.string(),
  pbid10: z.string(),
  pask10: z.string(),
  vbid10: z.string(),
  vask10: z.string(),
  dbid10: z.string(),
  dask10: z.string(),
});

export const overseasRealtimeDelayedOrderbookSchema = z.object({
  rsym: z.string(),
  symb: z.string(),
  zdiv: z.string(),
  xymd: z.string(),
  xhms: z.string(),
  kymd: z.string(),
  khms: z.string(),
  bvol: z.string(),
  avol: z.string(),
  bdvl: z.string(),
  advl: z.string(),
  pbid1: z.string(),
  pask1: z.string(),
  vbid1: z.string(),
  vask1: z.string(),
  dbid1: z.string(),
  dask1: z.string(),
});

export const overseasRealtimeExecutionSchema = z.object({
  rsym: z.string(),
  symb: z.string(),
  zdiv: z.string(),
  tymd: z.string(),
  xymd: z.string(),
  xhms: z.string(),
  kymd: z.string(),
  khms: z.string(),
  open: z.string(),
  high: z.string(),
  low: z.string(),
  last: z.string(),
  sign: z.string(),
  diff: z.string(),
  rate: z.string(),
  pbid: z.string(),
  pask: z.string(),
  vbid: z.string(),
  vask: z.string(),
  evol: z.string(),
  tvol: z.string(),
  tamt: z.string(),
  bivl: z.string(),
  asvl: z.string(),
  strn: z.string(),
  mtyp: z.string(),
});

export const overseasRealtimeExecutionNotificationSchema = z.object({
  custId: z.string(),
  acntNo: z.string(),
  oderNo: z.string(),
  ooderNo: z.string(),
  selnByovCls: z.string(),
  rctfCls: z.string(),
  oderKind2: z.string(),
  stckShrnIscd: z.string(),
  cntgQty: z.string(),
  cntgUnpr: z.string(),
  stckCntgHour: z.string(),
  rfusYn: z.string(),
  cntgYn: z.string(),
  acptYn: z.string(),
  brncNo: z.string(),
  oderQty: z.string(),
  acntName: z.string(),
  cntgIsnm: z.string(),
  oderCond: z.string(),
  debtGb: z.string(),
  debtDate: z.string(),
  startTm: z.string(),
  endTm: z.string(),
  tmDivTp: z.string(),
  cntgUnpr12: z.string(),
});

export type OverseasRealtimeOrderbookItem = z.infer<typeof overseasRealtimeOrderbookSchema>;
export type OverseasRealtimeDelayedOrderbookItem = z.infer<typeof overseasRealtimeDelayedOrderbookSchema>;
export type OverseasRealtimeExecutionItem = z.infer<typeof overseasRealtimeExecutionSchema>;
export type OverseasRealtimeExecutionNotificationItem = z.infer<typeof overseasRealtimeExecutionNotificationSchema>;
