import type { KisEndpointDefinition } from '../../core/types';

export const overseasMarketAnalysisEndpoints: KisEndpointDefinition[] = [
  {
    methodName: 'getStockPriceFluctuation',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/ranking/price-fluctuation',
    trId: 'HHDFS76260000',
    requestMap: {
      KEYB: 'keyb',
      AUTH: 'auth',
      EXCD: 'excd',
      GUBN: 'gubn',
      MIXN: 'mixn',
      VOL_RANG: 'volRang',
    },
    params: [
      { name: 'excd', required: true },
      { name: 'gubn', required: true },
      { name: 'mixn', required: true },
      { name: 'volRang', required: true },
      { name: 'keyb', required: false, defaultValue: '' },
      { name: 'auth', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getStockVolumeSurge',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/ranking/volume-surge',
    trId: 'HHDFS76270000',
    requestMap: {
      KEYB: 'keyb',
      AUTH: 'auth',
      EXCD: 'excd',
      MIXN: 'mixn',
      MINX: 'minx',
      VOL_RANG: 'volRang',
    },
    params: [
      { name: 'excd', required: true },
      { name: 'mixn', required: true },
      { name: 'volRang', required: true },
      { name: 'minx', required: true },
      { name: 'keyb', required: false, defaultValue: '' },
      { name: 'auth', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getStockBuyExecutionStrengthTop',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/ranking/volume-power',
    trId: 'HHDFS76280000',
    requestMap: {
      KEYB: 'keyb',
      AUTH: 'auth',
      EXCD: 'excd',
      NDAY: 'nday',
      VOL_RANG: 'volRang',
    },
    params: [
      { name: 'excd', required: true },
      { name: 'nday', required: true },
      { name: 'volRang', required: true },
      { name: 'keyb', required: false, defaultValue: '' },
      { name: 'auth', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getStockRiseDeclineRate',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/ranking/updown-rate',
    trId: 'HHDFS76290000',
    requestMap: {
      KEYB: 'keyb',
      AUTH: 'auth',
      EXCD: 'excd',
      GUBN: 'gubn',
      NDAY: 'nday',
      VOL_RANG: 'volRang',
    },
    params: [
      { name: 'excd', required: true },
      { name: 'gubn', required: true },
      { name: 'nday', required: true },
      { name: 'volRang', required: true },
      { name: 'keyb', required: false, defaultValue: '' },
      { name: 'auth', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getStockNewHighLowPrice',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/ranking/new-highlow',
    trId: 'HHDFS76300000',
    requestMap: {
      KEYB: 'keyb',
      AUTH: 'auth',
      EXCD: 'excd',
      GUBN: 'gubn',
      GUBN2: 'gubn2',
      NDAY: 'nday',
      VOL_RANG: 'volRang',
    },
    params: [
      { name: 'excd', required: true },
      { name: 'gubn', required: true },
      { name: 'gubn2', required: true },
      { name: 'nday', required: true },
      { name: 'volRang', required: true },
      { name: 'keyb', required: false, defaultValue: '' },
      { name: 'auth', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getStockTradingVolumeRank',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/ranking/trade-vol',
    trId: 'HHDFS76310010',
    requestMap: {
      KEYB: 'keyb',
      AUTH: 'auth',
      EXCD: 'excd',
      NDAY: 'nday',
      PRC1: 'prc1',
      PRC2: 'prc2',
      VOL_RANG: 'volRang',
    },
    params: [
      { name: 'excd', required: true },
      { name: 'nday', required: true },
      { name: 'prc1', required: true },
      { name: 'prc2', required: true },
      { name: 'volRang', required: true },
      { name: 'keyb', required: false, defaultValue: '' },
      { name: 'auth', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getStockTradingAmountRank',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/ranking/trade-pbmn',
    trId: 'HHDFS76320010',
    requestMap: {
      KEYB: 'keyb',
      AUTH: 'auth',
      EXCD: 'excd',
      NDAY: 'nday',
      VOL_RANG: 'volRang',
      PRC1: 'prc1',
      PRC2: 'prc2',
    },
    params: [
      { name: 'excd', required: true },
      { name: 'nday', required: true },
      { name: 'volRang', required: true },
      { name: 'prc1', required: true },
      { name: 'prc2', required: true },
      { name: 'keyb', required: false, defaultValue: '' },
      { name: 'auth', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getStockTradingIncreaseRateRank',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/ranking/trade-growth',
    trId: 'HHDFS76330000',
    requestMap: {
      KEYB: 'keyb',
      AUTH: 'auth',
      EXCD: 'excd',
      NDAY: 'nday',
      VOL_RANG: 'volRang',
    },
    params: [
      { name: 'excd', required: true },
      { name: 'nday', required: true },
      { name: 'volRang', required: true },
      { name: 'keyb', required: false, defaultValue: '' },
      { name: 'auth', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getStockTradingTurnoverRateRank',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/ranking/trade-turnover',
    trId: 'HHDFS76340000',
    requestMap: {
      KEYB: 'keyb',
      AUTH: 'auth',
      EXCD: 'excd',
      NDAY: 'nday',
      VOL_RANG: 'volRang',
    },
    params: [
      { name: 'excd', required: true },
      { name: 'nday', required: true },
      { name: 'volRang', required: true },
      { name: 'keyb', required: false, defaultValue: '' },
      { name: 'auth', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getStockMarketCapRank',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/ranking/market-cap',
    trId: 'HHDFS76350100',
    requestMap: {
      KEYB: 'keyb',
      AUTH: 'auth',
      EXCD: 'excd',
      VOL_RANG: 'volRang',
      CURR_GB: 'currGb',
    },
    params: [
      { name: 'excd', required: true },
      { name: 'volRang', required: true },
      { name: 'keyb', required: false, defaultValue: '' },
      { name: 'auth', required: false, defaultValue: '' },
      { name: 'currGb', required: false, defaultValue: '0' },
    ],
  },
  {
    methodName: 'getStockPeriodRightsInquiry',
    method: 'GET',
    path: '/uapi/overseas-price/v1/quotations/period-rights',
    trId: 'CTRGT011R',
    requestMap: {
      RGHT_TYPE_CD: 'rghtTypeCd',
      INQR_DVSN_CD: 'inqrDvsnCd',
      INQR_STRT_DT: 'inqrStrtDt',
      INQR_END_DT: 'inqrEndDt',
      PDNO: 'pdno',
      PRDT_TYPE_CD: 'prdtTypeCd',
      CTX_AREA_NK50: 'ctxAreaNk50',
      CTX_AREA_FK50: 'ctxAreaFk50',
    },
    params: [
      { name: 'rghtTypeCd', required: true },
      { name: 'inqrDvsnCd', required: true },
      { name: 'inqrStrtDt', required: true },
      { name: 'inqrEndDt', required: true },
      { name: 'pdno', required: true },
      { name: 'prdtTypeCd', required: true },
      { name: 'ctxAreaNk50', required: true },
      { name: 'ctxAreaFk50', required: true },
    ],
  },
  {
    methodName: 'getNewsAggregateTitle',
    method: 'GET',
    path: '/uapi/overseas-price/v1/quotations/news-title',
    trId: 'HHPSTH60100C1',
    requestMap: {
      INFO_GB: 'infoGb',
      CLASS_CD: 'classCd',
      NATION_CD: 'nationCd',
      EXCHANGE_CD: 'exchangeCd',
      SYMB: 'symb',
      DATA_DT: 'dataDt',
      DATA_TM: 'dataTm',
      CTS: 'cts',
    },
    params: [
      { name: 'infoGb', required: true },
      { name: 'classCd', required: true },
      { name: 'nationCd', required: true },
      { name: 'exchangeCd', required: true },
      { name: 'symb', required: true },
      { name: 'dataDt', required: true },
      { name: 'dataTm', required: true },
      { name: 'cts', required: true },
    ],
  },
  {
    methodName: 'getStockRightsAggregate',
    method: 'GET',
    path: '/uapi/overseas-price/v1/quotations/rights-by-ice',
    trId: 'HHDFS78330900',
    requestMap: {
      NCOD: 'ncod',
      SYMB: 'symb',
      ST_YMD: 'stYmd',
      ED_YMD: 'edYmd',
    },
    params: [
      { name: 'ncod', required: true },
      { name: 'symb', required: true },
      { name: 'stYmd', required: true },
      { name: 'edYmd', required: true },
    ],
  },
  {
    methodName: 'getStockCollateralLoanEligible',
    method: 'GET',
    path: '/uapi/overseas-price/v1/quotations/colable-by-company',
    trId: 'CTLN4050R',
    requestMap: {
      PDNO: 'pdno',
      PRDT_TYPE_CD: 'prdtTypeCd',
      INQR_STRT_DT: 'inqrStrtDt',
      INQR_END_DT: 'inqrEndDt',
      INQR_DVSN: 'inqrDvsn',
      NATN_CD: 'natnCd',
      INQR_SQN_DVSN: 'inqrSqnDvsn',
      RT_DVSN_CD: 'rtDvsnCd',
      RT: 'rt',
      LOAN_PSBL_YN: 'loanPsblYn',
      CTX_AREA_FK100: 'ctxAreaFk100',
      CTX_AREA_NK100: 'ctxAreaNk100',
    },
    params: [
      { name: 'pdno', required: true },
      { name: 'prdtTypeCd', required: true },
      { name: 'inqrStrtDt', required: true },
      { name: 'inqrEndDt', required: true },
      { name: 'inqrDvsn', required: true },
      { name: 'natnCd', required: true },
      { name: 'inqrSqnDvsn', required: true },
      { name: 'rtDvsnCd', required: true },
      { name: 'rt', required: true },
      { name: 'loanPsblYn', required: true },
      { name: 'ctxAreaFk100', required: true },
      { name: 'ctxAreaNk100', required: true },
    ],
  },
  {
    methodName: 'getBreakingNewsTitle',
    method: 'GET',
    path: '/uapi/overseas-price/v1/quotations/brknews-title',
    trId: 'FHKST01011801',
    requestMap: {
      FID_NEWS_OFER_ENTP_CODE: 'fidNewsOferEntpCode',
      FID_COND_MRKT_CLS_CODE: 'fidCondMrktClsCode',
      FID_INPUT_ISCD: 'fidInputIscd',
      FID_TITL_CNTT: 'fidTitlCntt',
      FID_INPUT_DATE_1: 'fidInputDate1',
      FID_INPUT_HOUR_1: 'fidInputHour1',
      FID_RANK_SORT_CLS_CODE: 'fidRankSortClsCode',
      FID_INPUT_SRNO: 'fidInputSrno',
      FID_COND_SCR_DIV_CODE: 'fidCondScrDivCode',
    },
    params: [
      { name: 'fidNewsOferEntpCode', required: true },
      { name: 'fidCondMrktClsCode', required: true },
      { name: 'fidInputIscd', required: true },
      { name: 'fidTitlCntt', required: true },
      { name: 'fidInputDate1', required: true },
      { name: 'fidInputHour1', required: true },
      { name: 'fidRankSortClsCode', required: true },
      { name: 'fidInputSrno', required: true },
      { name: 'fidCondScrDivCode', required: true },
    ],
  },
];

export type OverseasMarketAnalysisMethodName =
  | 'getStockPriceFluctuation'
  | 'getStockVolumeSurge'
  | 'getStockBuyExecutionStrengthTop'
  | 'getStockRiseDeclineRate'
  | 'getStockNewHighLowPrice'
  | 'getStockTradingVolumeRank'
  | 'getStockTradingAmountRank'
  | 'getStockTradingIncreaseRateRank'
  | 'getStockTradingTurnoverRateRank'
  | 'getStockMarketCapRank'
  | 'getStockPeriodRightsInquiry'
  | 'getNewsAggregateTitle'
  | 'getStockRightsAggregate'
  | 'getStockCollateralLoanEligible'
  | 'getBreakingNewsTitle';
