import type { KisEndpointDefinition } from '../../core/types';

export const overseasAccountEndpoints: KisEndpointDefinition[] = [
  {
    methodName: 'requestStockOrder',
    method: 'POST',
    path: '/uapi/overseas-stock/v1/trading/order',
    trId: 'TTTT1002U',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      OVRS_EXCG_CD: 'ovrsExcgCd',
      PDNO: 'pdno',
      ORD_QTY: 'ordQty',
      OVRS_ORD_UNPR: 'ovrsOrdUnpr',
      ORD_DVSN: 'ordDvsn',
      START_TIME: 'startTime',
      END_TIME: 'endTime',
      ALGO_ORD_TMD_DVSN_CD: 'algoOrdTmdDvsnCd',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'ovrsExcgCd', required: true },
      { name: 'pdno', required: true },
      { name: 'ordQty', required: true },
      { name: 'ovrsOrdUnpr', required: true },
      { name: 'ordDvsn', required: true },
      { name: 'startTime', required: false, defaultValue: '' },
      { name: 'endTime', required: false, defaultValue: '' },
      { name: 'algoOrdTmdDvsnCd', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'requestStockQuoteCorrection',
    method: 'POST',
    path: '/uapi/overseas-stock/v1/trading/order-rvsecncl',
    trId: 'TTTT1004U',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      OVRS_EXCG_CD: 'ovrsExcgCd',
      PDNO: 'pdno',
      ORGN_ODNO: 'orgnOdno',
      RVSE_CNCL_DVSN_CD: 'rvseCnclDvsnCd',
      ORD_QTY: 'ordQty',
      OVRS_ORD_UNPR: 'ovrsOrdUnpr',
      MGCO_APTM_ODNO: 'mgcoAptmOdno',
      ORD_SVR_DVSN_CD: 'ordSvrDvsnCd',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'ovrsExcgCd', required: true },
      { name: 'pdno', required: true },
      { name: 'orgnOdno', required: true },
      { name: 'rvseCnclDvsnCd', required: true },
      { name: 'ordQty', required: true },
      { name: 'ovrsOrdUnpr', required: true },
      { name: 'mgcoAptmOdno', required: false, defaultValue: '' },
      { name: 'ordSvrDvsnCd', required: false, defaultValue: '0' },
    ],
  },
  {
    methodName: 'requestStockReserveQuote',
    method: 'POST',
    path: '/uapi/overseas-stock/v1/trading/order-resv',
    trId: 'TTTT3014U',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      SLL_BUY_DVSN_CD: 'sllBuyDvsnCd',
      RVSE_CNCL_DVSN_CD: 'rvseCnclDvsnCd',
      PDNO: 'pdno',
      PRDT_TYPE_CD: 'prdtTypeCd',
      OVRS_EXCG_CD: 'ovrsExcgCd',
      FT_ORD_QTY: 'ftOrdQty',
      FT_ORD_UNPR3: 'ftOrdUnpr3',
      ORD_SVR_DVSN_CD: 'ordSvrDvsnCd',
      RSVN_ORD_RCIT_DT: 'rsvnOrdRcitDt',
      ORD_DVSN: 'ordDvsn',
      OVRS_RSVN_ODNO: 'ovrsRsvnOdno',
      ALGO_ORD_TMD_DVSN_CD: 'algoOrdTmdDvsnCd',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'pdno', required: true },
      { name: 'prdtTypeCd', required: true },
      { name: 'ovrsExcgCd', required: true },
      { name: 'ftOrdQty', required: true },
      { name: 'ftOrdUnpr3', required: true },
      { name: 'sllBuyDvsnCd', required: false, defaultValue: '' },
      { name: 'rvseCnclDvsnCd', required: false, defaultValue: '' },
      { name: 'ordSvrDvsnCd', required: false, defaultValue: '0' },
      { name: 'rsvnOrdRcitDt', required: false, defaultValue: '' },
      { name: 'ordDvsn', required: false, defaultValue: '' },
      { name: 'ovrsRsvnOdno', required: false, defaultValue: '' },
      { name: 'algoOrdTmdDvsnCd', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'requestStockReserveQuoteCorrection',
    method: 'POST',
    path: '/uapi/overseas-stock/v1/trading/order-resv-ccnl',
    trId: 'TTTT3017U',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      RSYN_ORD_RCIT_DT: 'rsynOrdRcitDt',
      OVRS_RSVN_ODNO: 'ovrsRsvnOdno',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'rsynOrdRcitDt', required: true },
      { name: 'ovrsRsvnOdno', required: true },
    ],
  },
  {
    methodName: 'requestOrderAfterDayTime',
    method: 'POST',
    path: '/uapi/overseas-stock/v1/trading/daytime-order',
    trId: 'TTTS6036U',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      OVRS_EXCG_CD: 'ovrsExcgCd',
      PDNO: 'pdno',
      ORD_QTY: 'ordQty',
      OVRS_ORD_UNPR: 'ovrsOrdUnpr',
      CTAC_TLNO: 'ctacTlno',
      MGCO_APTM_ODNO: 'mgcoAptmOdno',
      ORD_SVR_DVSN_CD: 'ordSvrDvsnCd',
      ORD_DVSN: 'ordDvsn',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'ovrsExcgCd', required: true },
      { name: 'pdno', required: true },
      { name: 'ordQty', required: true },
      { name: 'ovrsOrdUnpr', required: true },
      { name: 'ordDvsn', required: true },
      { name: 'ctacTlno', required: false, defaultValue: '' },
      { name: 'mgcoAptmOdno', required: false, defaultValue: '' },
      { name: 'ordSvrDvsnCd', required: false, defaultValue: '0' },
    ],
  },
  {
    methodName: 'cancelCorrectAfterDayTime',
    method: 'POST',
    path: '/uapi/overseas-stock/v1/trading/daytime-order-rvsecncl',
    trId: 'TTTS6038U',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      OVRS_EXCG_CD: 'ovrsExcgCd',
      PDNO: 'pdno',
      ORGN_ODNO: 'orgnOdno',
      RVSE_CNCL_DVSN_CD: 'rvseCnclDvsnCd',
      ORD_QTY: 'ordQty',
      OVRS_ORD_UNPR: 'ovrsOrdUnpr',
      CTAC_TLNO: 'ctacTlno',
      MGCO_APTM_ODNO: 'mgcoAptmOdno',
      ORD_SVR_DVSN_CD: 'ordSvrDvsnCd',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'ovrsExcgCd', required: true },
      { name: 'pdno', required: true },
      { name: 'orgnOdno', required: true },
      { name: 'rvseCnclDvsnCd', required: true },
      { name: 'ordQty', required: true },
      { name: 'ovrsOrdUnpr', required: true },
      { name: 'ctacTlno', required: false, defaultValue: '' },
      { name: 'mgcoAptmOdno', required: false, defaultValue: '' },
      { name: 'ordSvrDvsnCd', required: false, defaultValue: '0' },
    ],
  },
  {
    methodName: 'getBuyTradableAmount',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/trading/inquire-psamount',
    trId: 'TTTS3007R',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      OVRS_EXCG_CD: 'ovrsExcgCd',
      OVRS_ORD_UNPR: 'ovrsOrdUnpr',
      ITEM_CD: 'itemCd',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'ovrsExcgCd', required: true },
      { name: 'ovrsOrdUnpr', required: true },
      { name: 'itemCd', required: true },
    ],
  },
  {
    methodName: 'getStockNotConclusionHistory',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/trading/inquire-nccs',
    trId: 'TTTS3018R',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      OVRS_EXCG_CD: 'ovrsExcgCd',
      SORT_SQN: 'sortSqn',
      CTX_AREA_FK200: 'ctxAreaFk200',
      CTX_AREA_NK200: 'ctxAreaNk200',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'ovrsExcgCd', required: true },
      { name: 'sortSqn', required: true },
      { name: 'ctxAreaFk200', required: false, defaultValue: '' },
      { name: 'ctxAreaNk200', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getStockBalance',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/trading/inquire-balance',
    trId: 'TTTS3012R',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      OVRS_EXCG_CD: 'ovrsExcgCd',
      TR_CRCY_CD: 'trCrcyCd',
      CTX_AREA_FK200: 'ctxAreaFk200',
      CTX_AREA_NK200: 'ctxAreaNk200',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'ovrsExcgCd', required: true },
      { name: 'trCrcyCd', required: true },
      { name: 'ctxAreaFk200', required: false, defaultValue: '' },
      { name: 'ctxAreaNk200', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getStockConclusionHistory',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/trading/inquire-ccnl',
    trId: 'TTTS3035R',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      PDNO: 'pdno',
      ORD_STRT_DT: 'ordStrtDt',
      ORD_END_DT: 'ordEndDt',
      SLL_BUY_DVSN: 'sllBuyDvsn',
      CCLD_NCCS_DVSN: 'ccldNccsDvsn',
      OVRS_EXCG_CD: 'ovrsExcgCd',
      SORT_SQN: 'sortSqn',
      ORD_DT: 'ordDt',
      ORD_GNO_BRNO: 'ordGnoBrno',
      ODNO: 'odno',
      CTX_AREA_NK200: 'ctxAreaNk200',
      CTX_AREA_FK200: 'ctxAreaFk200',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'pdno', required: true },
      { name: 'ordStrtDt', required: true },
      { name: 'ordEndDt', required: true },
      { name: 'sllBuyDvsn', required: true },
      { name: 'ccldNccsDvsn', required: true },
      { name: 'ovrsExcgCd', required: true },
      { name: 'sortSqn', required: true },
      { name: 'ordDt', required: false, defaultValue: '' },
      { name: 'ordGnoBrno', required: false, defaultValue: '' },
      { name: 'odno', required: false, defaultValue: '' },
      { name: 'ctxAreaNk200', required: false, defaultValue: '' },
      { name: 'ctxAreaFk200', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getCurrentBalanceByConclusion',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/trading/inquire-present-balance',
    trId: 'CTRP6504R',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      WCRC_FRCR_DVSN_CD: 'wcrcFrcrDvsnCd',
      NATN_CD: 'natnCd',
      TR_MKET_CD: 'trMketCd',
      INQR_DVSN_CD: 'inqrDvsnCd',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'wcrcFrcrDvsnCd', required: true },
      { name: 'natnCd', required: true },
      { name: 'trMketCd', required: true },
      { name: 'inqrDvsnCd', required: true },
    ],
  },
  {
    methodName: 'getReserveOrders',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/trading/order-resv-list',
    trId: 'TTTT3039R',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      INQR_STRT_DT: 'inqrStrtDt',
      INQR_END_DT: 'inqrEndDt',
      INQR_DVSN_CD: 'inqrDvsnCd',
      PRDT_TYPE_CD: 'prdtTypeCd',
      OVRS_EXCG_CD: 'ovrsExcgCd',
      CTX_AREA_FK200: 'ctxAreaFk200',
      CTX_AREA_NK200: 'ctxAreaNk200',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'inqrStrtDt', required: true },
      { name: 'inqrEndDt', required: true },
      { name: 'inqrDvsnCd', required: true },
      { name: 'prdtTypeCd', required: true },
      { name: 'ovrsExcgCd', required: true },
      { name: 'ctxAreaFk200', required: false, defaultValue: '' },
      { name: 'ctxAreaNk200', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getBalanceBySettlement',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/trading/inquire-paymt-stdr-balance',
    trId: 'CTRP6010R',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      BASS_DT: 'bassDt',
      WCRC_FRCR_DVSN_CD: 'wcrcFrcrDvsnCd',
      INQR_DVSN_CD: 'inqrDvsnCd',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'bassDt', required: true },
      { name: 'wcrcFrcrDvsnCd', required: true },
      { name: 'inqrDvsnCd', required: true },
    ],
  },
  {
    methodName: 'getDailyTransactionHistory',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/trading/inquire-period-trans',
    trId: 'CTOS4001R',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      ERLM_STRT_DT: 'erlmStrtDt',
      ERLM_END_DT: 'erlmEndDt',
      OVRS_EXCG_CD: 'ovrsExcgCd',
      PDNO: 'pdno',
      SLL_BUY_DVSN_CD: 'sllBuyDvsnCd',
      LOAN_DVSN_CD: 'loanDvsnCd',
      CTX_AREA_FK100: 'ctxAreaFk100',
      CTX_AREA_NK100: 'ctxAreaNk100',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'erlmStrtDt', required: true },
      { name: 'erlmEndDt', required: true },
      { name: 'ovrsExcgCd', required: true },
      { name: 'pdno', required: true },
      { name: 'sllBuyDvsnCd', required: true },
      { name: 'loanDvsnCd', required: true },
      { name: 'ctxAreaFk100', required: false, defaultValue: '' },
      { name: 'ctxAreaNk100', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getPeriodProfitLoss',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/trading/inquire-period-profit',
    trId: 'TTTS3039R',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      OVRS_EXCG_CD: 'ovrsExcgCd',
      NATN_CD: 'natnCd',
      CRCY_CD: 'crcyCd',
      PDNO: 'pdno',
      INQR_STRT_DT: 'inqrStrtDt',
      INQR_END_DT: 'inqrEndDt',
      WCRC_FRCR_DVSN_CD: 'wcrcFrcrDvsnCd',
      CTX_AREA_FK200: 'ctxAreaFk200',
      CTX_AREA_NK200: 'ctxAreaNk200',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'ovrsExcgCd', required: true },
      { name: 'natnCd', required: true },
      { name: 'crcyCd', required: true },
      { name: 'pdno', required: true },
      { name: 'inqrStrtDt', required: true },
      { name: 'inqrEndDt', required: true },
      { name: 'wcrcFrcrDvsnCd', required: true },
      { name: 'ctxAreaFk200', required: false, defaultValue: '' },
      { name: 'ctxAreaNk200', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getMarginAggregate',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/trading/foreign-margin',
    trId: 'TTTC2101R',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
    ],
  },
  {
    methodName: 'getLimitOrderNumber',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/trading/algo-ordno',
    trId: 'TTTS6058R',
    requestMap: {
      TRAD_DT: 'tradDt',
      CANO: 'cano',
      ACNO_PRDT_CD: 'acnoPrdtCd',
      CTX_AREA_NK200: 'ctxAreaNk200',
      CTX_AREA_FK200: 'ctxAreaFk200',
    },
    params: [
      { name: 'tradDt', required: true },
      { name: 'cano', required: true },
      { name: 'acnoPrdtCd', required: true },
      { name: 'ctxAreaNk200', required: false, defaultValue: '' },
      { name: 'ctxAreaFk200', required: false, defaultValue: '' },
    ],
  },
  {
    methodName: 'getLimitOrderExecutionHistory',
    method: 'GET',
    path: '/uapi/overseas-stock/v1/trading/inquire-algo-ccnl',
    trId: 'TTTS6059R',
    requestMap: {
      CANO: 'cano',
      ACNT_PRDT_CD: 'acntPrdtCd',
      ORD_DT: 'ordDt',
      ORD_GNO_BRNO: 'ordGnoBrno',
      ODNO: 'odno',
      TTLZ_ICLD_YN: 'ttlzIcldYn',
      CTX_AREA_NK200: 'ctxAreaNk200',
      CTX_AREA_FK200: 'ctxAreaFk200',
    },
    params: [
      { name: 'cano', required: true },
      { name: 'acntPrdtCd', required: true },
      { name: 'ordDt', required: true },
      { name: 'odno', required: true },
      { name: 'ordGnoBrno', required: false, defaultValue: '' },
      { name: 'ttlzIcldYn', required: false, defaultValue: '' },
      { name: 'ctxAreaNk200', required: false, defaultValue: '' },
      { name: 'ctxAreaFk200', required: false, defaultValue: '' },
    ],
  },
];

export type OverseasAccountMethodName =
  | 'requestStockOrder'
  | 'requestStockQuoteCorrection'
  | 'requestStockReserveQuote'
  | 'requestStockReserveQuoteCorrection'
  | 'requestOrderAfterDayTime'
  | 'cancelCorrectAfterDayTime'
  | 'getBuyTradableAmount'
  | 'getStockNotConclusionHistory'
  | 'getStockBalance'
  | 'getStockConclusionHistory'
  | 'getCurrentBalanceByConclusion'
  | 'getReserveOrders'
  | 'getBalanceBySettlement'
  | 'getDailyTransactionHistory'
  | 'getPeriodProfitLoss'
  | 'getMarginAggregate'
  | 'getLimitOrderNumber'
  | 'getLimitOrderExecutionHistory';
